sudo: required
services:
  - docker

before_install:
  - docker build -t p4fun/react-test ./client -f ./client/Dockerfile.dev

script:
  - docker run  p4fun/react-test npm test -- --coverage

after_success:
  - docker build -t p4fun/multi-client ./client
  - docker build -t p4fun/multi-nginx ./nginx
  - docker build -t p4fun/multi-server ./server
  - docker build -t p4fun/multi-worker ./worker
  # Log in to the docker cli
  - echo '$DOCKER_PASSWORD' | docker login -u '$DOCKER_ID' --password-stdin
  # Take those images and push them to docker hub
  - docker push p4fun/multi-client
  - docker push p4fun/multi-nginx
  - docker push p4fun/multi-server
  - docker push p4fun/multi-worker
